language: c
sudo: false
matrix:
  include:
    - os: linux
      services:
        - docker
      install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
      script: bash -ex ./.travis-docker.sh
      env:
        global:
          - PACKAGE="ppx_deriving"
  	  - TESTS="true"
        matrix:
	  - DISTRO="alpine" OCAML_VERSION="4.06.0"
	  - DISTRO="alpine" OCAML_VERSION="4.05.0"
	  - DISTRO="alpine" OCAML_VERSION="4.04.2"
	  - DISTRO="alpine" OCAML_VERSION="4.04.1"
	  - DISTRO="alpine" OCAML_VERSION="4.04.0"
	  - DISTRO="debian-stable" OCAML_VERSION="4.03.0"
	  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.02.3"
    - os: osx
      install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
      script: bash -ex ./.travis-opam.sh
      env:
        global:
          - PACKAGE="ppx_deriving"
          - TESTS="true"
        matrix:
          - OCAML_VERSION="4.05.0"
